### ISSUE TITLE
Wrong site behavior on Amazon Kindle Fire HDX 7

### ISSUE THREAD

**Issue by v-lebedenko** [SarineTechnologies/sarine.viewer.templates#16]
**Device:** Amazon Kindle Fire HDX 7
**OS:** android
**Browser:** native 
**Link:** http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#
**Version:** 1.0.1

---

#### Steps to reproduce
1. open http://api-2.qa.sarine.com/viewer/v1/0EXAMPLE0/0EXECUTE0#

#### Actual result
site stopped. not clickable

#### Expected result
site should work propperly

![321](https://cloud.githubusercontent.com/assets/10975093/6439820/6df4b00c-c0df-11e4-96e1-25f18dfdae64.png)

**Comment by a-kolomiets** [comment]
![2015-03-03_20-01-51](https://cloud.githubusercontent.com/assets/5763168/6468826/93e5878a-c1e0-11e4-8fd4-35f1d067e2cc.png)

It looks like the issue is on the sarine viewer side. We checked the simple template and the page is freezes as well. 

URL that we used is http://s3.amazonaws.com/m.dev.sarineloupe.com/qa2/univiewer/sample4.html
